/**
 * CoinGecko coin id -> Binance USDT spot pair.
 * Used for candle/chart failover and live streams.
 */
export const BINANCE_PAIRS: Record<string, string> = {
  bitcoin: 'BTCUSDT',
  ethereum: 'ETHUSDT',
  binancecoin: 'BNBUSDT',
  solana: 'SOLUSDT',
  ripple: 'XRPUSDT',
  cardano: 'ADAUSDT',
  dogecoin: 'DOGEUSDT',
  'avalanche-2': 'AVAXUSDT',
  polkadot: 'DOTUSDT',
  chainlink: 'LINKUSDT',
  'matic-network': 'MATICUSDT',
  polygon: 'POLUSDT',
  tron: 'TRXUSDT',
  litecoin: 'LTCUSDT',
  'shiba-inu': 'SHIBUSDT',
  uniswap: 'UNIUSDT',
  cosmos: 'ATOMUSDT',
  stellar: 'XLMUSDT',
  'near-protocol': 'NEARUSDT',
  aptos: 'APTUSDT',
  arbitrum: 'ARBUSDT',
  optimism: 'OPUSDT',
  'the-open-network': 'TONUSDT',
  pepe: 'PEPEUSDT',
  sui: 'SUIUSDT',
  'internet-computer': 'ICPUSDT',
  filecoin: 'FILUSDT',
  'hedera-hashgraph': 'HBARUSDT',
  'injective-protocol': 'INJUSDT',
  algorand: 'ALGOUSDT',
  fantom: 'FTMUSDT',
  'render-token': 'RENDERUSDT',
  sei: 'SEIUSDT',
};
